import { Open_Sans } from "next/font/google";
import "./globals.css";

const open_sans = Open_Sans({ subsets: ["latin"], weight: "400" });

export const metadata = {
  icons: {
    icon: "/icon.png",
  },
  title: "Bistro Verve",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${open_sans.className} bg-lime-50 selection:bg-gray-400`}
      >
        {children}
      </body>
    </html>
  );
}
